server:
  port: 1082
spring:
  cloud:
    gateway:
      routes[0]:
        id: users-status-check
        uri: http://localhost:9191
        predicates[0]: Path=/users/status/check
        predicates[1]: Method=GET
        filter[0]: RemoveRequestHeader=Cookie
      routes[1]:
        id: department-all
        uri: http://localhost:9192
        predicates[0]: Path=/department/all
        predicates[1]: Method=GET
        filter[1]: RemoveRequestHeader=Cookie
      routes[2]:
        id: employee-all
        uri: http://localhost:9093
        predicates[0]: Path=/employee/all
        predicates[1]: Method=GET
        filter[1]: RemoveRequestHeader=Cookie

                    
        